package be.brusselsbook.sql;

import static be.brusselsbook.sql.BookUserAccess.INSERT;
import static be.brusselsbook.sql.BookUserAccess.SELECTBY;

import java.sql.ResultSet;
import java.sql.SQLException;

import be.brusselsbook.data.BookUser;
import be.brusselsbook.sql.exception.DatabaseAccessException;

public class BookUserAccessImpl implements BookUserAccess {

	private static BookUser map(ResultSet resultSet) throws SQLException {
		BookUser bookUser = new BookUser();
		bookUser.setUid(resultSet.getLong("UID"));
		bookUser.setEmailAddress(resultSet.getString("EmailAddress"));
		bookUser.setUsername(resultSet.getString("Username"));
		bookUser.setPassword(resultSet.getString("Pwd"));
		bookUser.setRegistrationDate(resultSet.getTimestamp("RegistrationDate"));
		return bookUser;
	}

	private AccessFactory accessFactory;

	public BookUserAccessImpl(AccessFactory accessFactory) {
		this.accessFactory = accessFactory;
	}

	private BookUser userWith(String sqlQuery, Object object) throws DatabaseAccessException {
		BookUser bookUser = null;
		ResultSet resultSet = AccessUtils.executeQuery(accessFactory, sqlQuery, object);
		try {
			if (resultSet.next()) {
				bookUser = map(resultSet);
			}
		} catch (SQLException e) {
			throw new DatabaseAccessException(e);
		}
		AccessUtils.close(resultSet);
		return bookUser;
	}

	@Override
	public BookUser create(String email, String username, String password) throws DatabaseAccessException {
		BookUser createdUser = null;
		ResultSet autoGeneratedValues = AccessUtils.executeInsert(accessFactory, INSERT(), email, username, password);
		try {
			if (autoGeneratedValues.next()) {
				Long uid = autoGeneratedValues.getLong(1);
				createdUser = userWithUid(uid);
			} else {
				throw new DatabaseAccessException("Failed to generated the BookUser UID.");
			}
		} catch (SQLException e) {
			throw new DatabaseAccessException(e);
		}
		AccessUtils.close(autoGeneratedValues);
		return createdUser;
	}

	@Override
	public BookUser userWithEmail(String email) throws DatabaseAccessException {
		return userWith(SELECTBY(EMAILADDRESS), email);
	}

	@Override
	public BookUser userWithUsername(String username) {
		return userWith(SELECTBY(USERNAME), username);
	}

	@Override
	public BookUser userWithUid(Long uid) {
		return userWithUid(uid.toString());
	}

	@Override
	public BookUser userWithUid(String uid) {
		return userWith(SELECTBY(UID), uid);
	}

}
